- name: create instance
  hosts: localhost
  connection: local
  vars:
    acs_access_key: XXXXXXXXXX
    acs_secret_access_key: XXXXXXXXXX
    region: cn-shenzhen
    instance_ids: i-94dehop6n
    instance_tags:
    - tag_key: create_test
      tag_value: '0.01'
    force: False
    stage: created
  tasks:
    - name: create instance
      ecs:
        acs_access_key_id: '{{ acs_access_key }}'
        acs_secret_access_key: '{{ acs_secret_access_key }}'
        state: '{{ state }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image: '{{ image }}'
        instance_type: '{{ instance_type }}'
        group_id: '{{ group_id }}'
        io_optimized: '{{ io_optimized }}'
        vswitch_id: '{{ vswitch_id }}'
        instance_name: '{{ instance_name }}'
        description: '{{ description }}'
        internet_data: '{{ internet_data }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        system_disk: '{{ system_disk }}'
        volumes: '{{ volumes }}'
        count: '{{ count }}'
        allocate_public_ip: '{{ allocate_public_ip }}'
        bind_eip: '{{ bind_eip }}'
        instance_tags: '{{ instance_tags }}'
