- name: start stop restart instance
  hosts: localhost
  connection: local
  vars: 
    acs_access_key: XXXXXXXXX
    acs_secret_access_key: XXXXXXXXX
    region: ap-southeast-1
    instance_ids: i-t4n3gf6h0znf6f5h01ic
    force: False
    state: running
  tasks: 
    - name: start instance
      ecs:
        acs_access_key_id: '{{ acs_access_key }}'
        acs_secret_access_key: '{{ acs_secret_access_key }}'
        region: '{{ region }}'
        instance_ids: '{{ instance_ids }}'
        instance_tags: '{{ instance_tags }}'
        state: '{{ state }}'
